### ISSUE TITLE
Documentation and package.json Issues

### ISSUE THREAD

**Issue by GargantulaKon** [kyle-mccarthy/nest-next#1]
In my terminal, I tried to start the example app within the example folder. I tried to start it by following the ReadMe by running yarn. I got an error about Nest-Next missing. I then run yarn add nest-next. I tried running yarn again. That worked, but when I tried to run yarn dev. I then get another error for /bin/sh: nodemon: command not found. I then try adding yarn add nodemon --save-dev. I tried running yarn and finally I didn't get any errors. I was then able to run yarn dev.

When I was getting ready to submit a pull request, I noticed yalc. I'm not familiar with yalc so then I noticed that I needed to add it globally with yarn global add yalc. Adding yalc didn't seem to fix the issues though. What is the globally installed app requirements before running your project with the instructions you provided? I know yarn for sure.

**Comment by kyle-mccarthy** [comment]
Hey thanks for checking this out! Thank you for letting me know about the problems with the package.json file in the example project. Originally I had stripped down one of my personal projects for the example but didn't do a good enough job of making sure you had everything you needed. I went in and fixed the reference for the `nest-next` package and added `nodemon` as a dev dependency.  Let me know if you have any other issues with the example. 

Also I am going to create a wiki page for a step by step tutorial style guide, and will update this issue when it is ready.  However, the main readme does contain all you need to get started with the package but it does assume a familiarity with nest and next.  With the wiki I will try to write it in a way that doesn't assume there is a deep knowledge of next.

**Comment by GargantulaKon** [comment]
You're welcome. I'm learning Nest and Next through your example app so thank you for creating this package. Is Yalc not needed then? I'm looking forward to your Wiki page.

**Comment by kyle-mccarthy** [comment]
I apologize this is long overdue. To answer your question yalc isn't needed at all. I actually just use that to test out changes I make to the package before publishing it to NPM. That should have been removed prior to being pushed to git.

I updated the example and removed a ton of complexity. It can essentially be used as a started to quickly setup the project.

I also wrote a setup guide that basically takes your step by step to create the example from scratch. You can look at it here: https://github.com/kyle-mccarthy/nest-next/wiki/Setup-Guide
