### ISSUE TITLE
Cant start the app

### ISSUE THREAD

**Issue by rnasif** [kyle-mccarthy/nest-next#11]
Hi there i am having this error when compiling:

Argument of type 'INestApplication & INestExpressApplication' is not assignable to parameter of type 'INestApplication'.
  Property 'enableShutdownHooks' is missing in type 'INestApplication & INestExpressApplication' but required in type 'INestApplication'.

this is my code:

`import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { HttpExceptionFilter } from './shared/filters/http-exception.filter';
import { RenderModule } from 'nest-next';
import Next from 'next';
const dev = AppModule.isDev;

declare const module: any;

async function bootstrap() {
    const nextServer = Next({ dev });
    
    await nextServer.prepare();

    const app = await NestFactory.create(AppModule);
    const renderer = app.get(RenderModule);
    renderer.register(app, nextServer); // here is the error
    const hostDomain = AppModule.isDev ? `${AppModule.host}:${AppModule.port}` : AppModule.host;

    const swaggerOptions = new DocumentBuilder()
        .setTitle('Nest MEAN')
        .setDescription('API Documentation')
        .setVersion('1.0.0')
        .setHost(hostDomain.split('//')[1])
        .setSchemes(AppModule.isDev ? 'http' : 'https')
        .setBasePath('/api')
        .addBearerAuth('Authorization', 'header')
        .build();

    const swaggerDoc = SwaggerModule.createDocument(app, swaggerOptions);

    SwaggerModule.setup('/api/docs', app, swaggerDoc, {
        swaggerUrl: `${hostDomain}/api/docs-json`,
        explorer: true,
        swaggerOptions: {
            docExpansion: 'list',
            filter: true,
            showRequestDuration: true,
        },
    });

    if (module.hot) {
        module.hot.accept();
        module.hot.dispose(() => app.close());
    }

    app.setGlobalPrefix('api');
    app.useGlobalFilters(new HttpExceptionFilter());

    await app.listen(AppModule.port);
}

bootstrap();
`

**Comment by kyle-mccarthy** [comment]
Hi could you please provide me with the full stack trace for the error as well as the versions of nest, next and nest-next that you are using?

**Comment by rnasif** [comment]
Hi kyle thanks for the quick response! 

I am trying to implement next on this project [https://github.com/nartc/nest-mean](https://github.com/nartc/nest-mean) 

full stack trace:
> /mnt/c/Users/Rodrigo/nodejs/nest-mean-master/server/node_modules/ts-node/src/index.ts:261
>     return new TSError(diagnosticText, diagnosticCodes)
>            ^
> TSError: ⨯ Unable to compile TypeScript:
> src/main.ts(18,23): error TS2345: Argument of type 'INestApplication & INestExpressApplication' is not assignable to parameter of type 'INestApplication'.
>   Property 'enableShutdownHooks' is missing in type 'INestApplication & INestExpressApplication'.
> 
>     at createTSError (/mnt/c/Users/Rodrigo/nodejs/nest-mean-master/server/node_modules/ts-node/src/index.ts:261:12)
>     at getOutput (/mnt/c/Users/Rodrigo/nodejs/nest-mean-master/server/node_modules/ts-node/src/index.ts:367:40)
>     at Object.compile (/mnt/c/Users/Rodrigo/nodejs/nest-mean-master/server/node_modules/ts-node/src/index.ts:558:11)
>     at Module.m._compile (/mnt/c/Users/Rodrigo/nodejs/nest-mean-master/server/node_modules/ts-node/src/index.ts:439:43)
>     at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Object.require.extensions.(anonymous function) [as .ts] (/mnt/c/Users/Rodrigo/nodejs/nest-mean-master/server/node_modules/ts-node/src/index.ts:442:12)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)

Nest: 5.4.0
Next: 8.0.3
nest-next: 0.6.3

**Comment by kyle-mccarthy** [comment]
Ah okay so in version `0.6` of nest-next I upgraded the the dependencies to add support for nest 6; however, version `0.5.x` still uses nest 5. So if you are unable to upgrade to nest 6 you can do a `yarn add nest-next@0.5.0` and be able to use it.

**Comment by kyle-mccarthy** [comment]
I am going to close this since it's related to and outdated version of nest. Please reopen it if you continue to have similar issues after upgrading nest.
