### ISSUE TITLE
seperate API routes and client routes?

### ISSUE THREAD

**Issue by tconroy** [kyle-mccarthy/nest-next#12]
Hey there,
I'm new to nest/next but would like to use them together, where nest serves all `/api/` routes and next serves all client routes (ie all `GET` requests that aren't prefixed with`/api/`). 

It seems like with this plugin nest tries to handle all the routes. How can I configure the routing to send all non-/api/ GET's to next and everything else to nest?

**Comment by kyle-mccarthy** [comment]
Hi, Nest will try to handle all of the routes that Next does not render. So as an example, you have a single controller responsible for returning information about a user. In this controller you want to have a route that returns a rendered user page but also want a route that just returns JSON data about that user.

```
@Controller('user')
export class UserController {

  private userData() {
    return {
      name: "tconroy"
    };
  }

  @Render('UserProfilePage')
  @Get(':user')
  public getUserPage(@Param('user') user: string) {
    // this will give the data to getInitialProps in your file "UserProfilePage"
    return this.userData();
  }
  
  @Get(':user/json')
  public getUserJson(@Param('user') user: string) {
    // this will just return JSON data
    return this.userData();
  }
}
```

**Comment by kyle-mccarthy** [comment]
I am going to close this since there hasn't been any additional feedback or questions.
