### ISSUE TITLE
HMR breaks when using lower-case filenames for pages

### ISSUE THREAD

**Issue by sanjaytwisk** [kyle-mccarthy/nest-next#14]
I am not quite sure if this is related to NestJS or the renderer, but when using lower-case filenames for pages (e.g index.tsx), hot module reload breaks and content is not updated.

**Comment by kyle-mccarthy** [comment]
Would you be able to provide me a with a minimal reproducible example?

**Comment by sanjaytwisk** [comment]
Sorry for the late reply. Cannot seem to reproduce the issue, even though I have been struggling with it for a full day before I found it... Only difference is that I deleted `node_modules` and installed all deps again.
