### ISSUE TITLE
the build process doesn't end

### ISSUE THREAD

**Issue by Linjovi** [kyle-mccarthy/nest-next#17]
Hi, I encountered a very strange problem that when I used the package 'socket.io-client' in my project, the build process did not end up and exit, but will instead stay after the 'Compiled successfully' info.
```
import io from "socket.io-client";
const socket = io("http://localhost:4000");
```
![image](https://user-images.githubusercontent.com/18590421/62352861-c1c32380-b53b-11e9-833e-f677989ed428.png)
But when I use `ctrl+c` and `npm run start`, the project seems to be working quite well. I don't know much about Babel, and can't solve this problem.

**Comment by kyle-mccarthy** [comment]
Would you be able to make a minimal reproducible example as a repo and I can take a look at this?

**Comment by Linjovi** [comment]
Thanks for reply, I just added the dependent 'socket.io-client' and added the following code
```
import io from "socket.io-client";
const socket = io("http://localhost:4000");
``` 
to the example/pages/views/index.tsx you gave, and without making any other changes, then that's what happens.
Or you can see the code in this repository at 'pages/components/Operator.tsx'：https://github.com/Linjovi/git-repos-manager
My node version is 11.12.0 if it's relevant

**Comment by kyle-mccarthy** [comment]
Are you still having this issue? I just tried this with the new release, a socket-io server running on localhost:4000 and a client created in the index page file and didn't have any problems.

If the problem persists, I think you may be having an issue with creating the client socket outside the effect. Creating the socket where you are could be causing a problem when the page is rendered with SSR.

I specifically tested with this code:

```typescript
React.useEffect(() => {
  const socket = io('127.0.0.1:4000');
  
  return () => {
    socket.close();
  };
});
```

You'll want to return a closure that closes the socket when it is called so react cleans up the resource that was created.

**Comment by Linjovi** [comment]
Thanks, you solved my problem perfectly, it looks like I made a stupid mistake orz.
