### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by kyctarnik** [kyle-mccarthy/nest-next#19]
I tried many times but didn't find solution about nested routes width this module.
Example: i want to set router like /auth/success/ where success - is another component dependents from route pass
`<section>
    <Switch>
      <Route path="/auth/success" component={LoginSuccess} />
      <Route path="/auth/failed" component={LoginFailed} />
      <Route component={LoginForm} />
    </Switch>
</section>`

**Comment by kyle-mccarthy** [comment]
I haven't actually tried this before. Would you provide me with an example of how this would be done with just nextjs? If you can show me how they do it, I can look into how it may be done with nest-next.

**Comment by kyctarnik** [comment]
Nevermind, found a solution width Redux and connected-react-router
store.tsx
import { createStore, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import createRootReducer from './reducer';
import { createBrowserHistory, createMemoryHistory, History } from 'history'

export let history: History;
export function createHistory(baseUrl: string = '/'): History {
	if (typeof window === 'undefined') {
		history = createMemoryHistory({
			initialEntries: [baseUrl]
		});
	}
	if (!history) {
		history = createBrowserHistory();
	}
	return history;
}
const initStore = (initialState?: any, options?: any) => {
	createHistory(options.asPath);
	return createStore(
		createRootReducer(history),
		initialState,
		composeWithDevTools(
			applyMiddleware(
				routerMiddleware(history),
			),
		),
	);
};
export default initStore;
