### ISSUE TITLE
Example for Next.js 9

### ISSUE THREAD

**Issue by webberwang** [kyle-mccarthy/nest-next#20]
Next.js 9 overrides `tsconfig.json`, makes it difficult to get it working. Is it possible to provide an example for 9?

**Comment by kyle-mccarthy** [comment]
Yeah I actually had an issue with that went migrating to next 9 so I rewrote [the example](https://github.com/kyle-mccarthy/nest-next/tree/master/example) to make it compatible. Basically, you need to have a [primary tsconfig.json](https://github.com/kyle-mccarthy/nest-next/blob/master/example/tsconfig.json), which next modifies, and then an additional [tsconfig.server.json](https://github.com/kyle-mccarthy/nest-next/blob/master/example/tsconfig.server.json) for the server side code.
