### ISSUE TITLE
 Argument of type 'import' is not assignable to parameter

### ISSUE THREAD

**Issue by dotai2012** [kyle-mccarthy/nest-next#22]
Hi there, I think the plugin has some problems with type checking. I copy the example code and it produce the error:

`D:\Work\example\node_modules\ts-node\src\index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/main.ts:16:29 - error TS2345: Argument of type 'import("D:/Work/example/node_modules/next/dist/next-server/server/next-server").default' is not assignable to parameter of type 'import("D:/Work/example/node_modules/next-server/dist/server/next-server").default'.
renderer.register(server, app);
`

**Comment by kyle-mccarthy** [comment]
What version of nest, next, and nest-next are you using?

**Comment by dotai2012** [comment]
![Argument-error](https://user-images.githubusercontent.com/12532557/65298501-995dab80-db20-11e9-8e36-e3b13211fd40.png)

Sure, I created a repo for this: https://github.com/dotai2012/nest-next-error

Typescript version I used: 3.6.2
