### ISSUE TITLE
Next <Link> re-render when user navigating

### ISSUE THREAD

**Issue by dotai2012** [kyle-mccarthy/nest-next#23]
Thank you very much for creating this module. However, I found a bug that when I click on a link (use Next Link component), the page flashed. It should be render the pages seamlessly right?

**Comment by kyle-mccarthy** [comment]
Can you provide me with a minimal reproducible sample repository?

**Comment by dotai2012** [comment]
I created a repo for this: https://github.com/dotai2012/nest-next-error

Anyway, I somehow fixed this issue by duplicate the files from ./page/views to ./page -> The issue's gone. However, I think this is not a good solution

**Comment by kyle-mccarthy** [comment]
Hey so I was looking into this today, but I haven't actually been able to see the difference between pages served from ./pages/views vs ./pages in the example repo. 

I have attached two gifs showing what I see visually between the two and they seem identical. Let me know if I am just missing something, thanks!

__Served from /pages/views__
![views-dir-2019-09-24 16 06 41](https://user-images.githubusercontent.com/7758522/65550678-bcec7180-dee5-11e9-9791-96d7fff00b14.gif)

__Served from /pages__
![pages-dir-2019-09-24 16 04 08](https://user-images.githubusercontent.com/7758522/65550698-c37ae900-dee5-11e9-8f6c-b31e5d42ab95.gif)

**Comment by AndrewKvalheim** [comment]
The problem is the page reload. It's visible in the screenshots; notice that the log is cleared and timings are reset.

Client-side navigation works as expected if I adhere to Next.js file naming conventions—use `viewsDir: null` and name page source files after their routes, i.e. typically lowercase.

**Comment by kyle-mccarthy** [comment]
In one of the screenshots the viewsDir is set to null and the source files are named after the route. The only difference is that the files are capitalized. Regardless the logs and cleared in both screenshots. 

Can you update your example to show the intended behavior you are describing? I am happy to make any changes but want to understand the problem.

**Comment by kyle-mccarthy** [comment]
@AndrewKvalheim @dotai2012 Okay I looked into this more and I understand the problem and what the intended behavior is. I was also actually able to replicate this with just next using a custom server. It looks like if the setup deviates from the standard (like Andrew pointed out) and the pages aren't lowercase and matching the name of the route a reload occurs on navigation. I am going to try to put together a sample and will open an issue in the next repo.

**Comment by kyle-mccarthy** [comment]
After going through their issue tracker it has become apparent that this is actually the intended functionality. In a `Link` component the `href` maps to the path inside the pages directory. See [this issue](https://github.com/zeit/next.js/issues/8085) and [their docs](https://github.com/zeit/next.js#dynamic-routing).

To make it work `href` needs to map to the path inside your pages directory and the filename casing needs to be correct. To have the link then map to the right route you need to use `as`. 

For example, here is the code that I was using previously that **is incorrect** when the file path is `pages/About.js`:

```jsx
<Link href="/about"><a>About</a></Link>
```

The following is the correct way:

```jsx
<Link href="/About" as="/about"><a>About</a></Link>
```

If you serve your pages out of `pages/views` and the path is `pages/views/About.js` you would have:

```jsx
<Link href="/views/About.js" as="/about"><a>About</a></Link>
```
