### ISSUE TITLE
Different next/next-server versions cause TS2345 for renderer.register

### ISSUE THREAD

**Issue by AmazingTurtle** [kyle-mccarthy/nest-next#24]
**Describe the bug**
RenderModule is using `Server` from `next-server`.
Typescript doesn't accept the second paramter of this call: `renderer.register(server, app);`
This is the erorr that comes up when compiling:

```
TSError: ⨯ Unable to compile TypeScript:
src/main.ts(16,29): error TS2345: Argument of type 'import("my-project-folder/node_modules/next/dist/next-server/server/next-server").default' is not assignable to parameter of type 'import("my-project-folder/node_modules/next-serve
r/dist/server/next-server").default'.
  Types have separate declarations of a private property 'compression'.
```

**Expected behavior**
RenderModule should use `Server` from `next`;
See `examlple/` in this repo, it's trying to pass Server `app` created by `Next` call which comes from `import Next from 'next';` but RenderModule is using `next-server` and those types are incompatible.

**To Reproduce**

Repository URL:  https://github.com/kyle-mccarthy/nest-next/tree/12651f7d7bcb5b9b76f3384ff323ca920bad754f/example

**Version**
- next.js: `next@9.0.6`, `next-server@9.0.5`
- nest: `@nestjs/common@6.7.2`, `@nestjs/core@6.7.2`
- nest-next: `nest-next@9.0.0-beta.0`

**Additional context**
See https://github.com/kyle-mccarthy/nest-next/blob/565d77c30adf059f7001e1555f7802fb257e400b/lib/render.module.ts#L2

**Please read**: I have found that the issue is that next was configured to use `^9.0.6`. However `next@9.0.6`, comes with `next-server@9.0.5` and causes this error. It is questionable if this is a bug related to `nest-next`. My temporary fix is to lock both next and next-server to `9.0.5`.

**Comment by kyle-mccarthy** [comment]
This looks like it may be related to the following PR from the next repo and was apart of their 9.0.6 milestone. https://github.com/zeit/next.js/pull/8613

Unfortunately, it looks like they removed the entire package but only made it a patch level version change? I will update this package to be compatible but it may break for everyone still on <=9.0.6.

**Comment by kyle-mccarthy** [comment]
Hey a new version was just released. If you upgrade next to 9.0.6 as well as nest-next to 9.0.6, it should resolve the issue. Let me know if the problem persists, thanks!

**Comment by kyle-mccarthy** [comment]
I am going to close this as it seems to be resolved. Please let me know if you are still encountering it and I will reopen this.
