### ISSUE TITLE
Type mismatch server.ts INestApplication & INestAppliactionSubset

### ISSUE THREAD

**Issue by webberwang** [kyle-mccarthy/nest-next#27]
**Describe the bug**
```javascript
NestFactory.create(): INestAppliactionSubset
```

doesn't match

```javascript
renderer.register(server: INestAppliactionSubset)
```

```javascript
(async () => {
  const app = next({
    dev: true,
  });
  const handler = routes.getRequestHandler(app);

  await app.prepare();

  const server = await NestFactory.create(AppModule);

  const renderer = server.get(RenderModule);

  // this won't compile either
  renderer.register(server as any, app);

  await server.use(handler).listen(3000);
})();
```

<img width="1743" alt="codelab-ui-nestjs____Code_UIB_codelab-ui-nestjs__-_____packages_core_server_server_ts" src="https://user-images.githubusercontent.com/26264925/67523185-fa6a2900-f662-11e9-9b32-fc25f07ccf84.png">

**Expected behavior**
match type

**To Reproduce**
Repository URL: 

**Version**
- next.js: 9.1.1
- nest: 6.5.3
- nest-next: 9.0.6

**Comment by kyle-mccarthy** [comment]
It looks like you are using an older version if nestjs, can you upgrade to 6.8.5? That should resolve the issue. They added [redirect](https://github.com/nestjs/nest/commit/f4d3c03d6ba909146b62ac63cdf2d472bccddc0e#diff-5d7c4c18e789467d36c834373e5aac59) and [getType](https://github.com/nestjs/nest/commit/35635be02ebdee5f680beb00e95e4cd12798aa1b#diff-5d7c4c18e789467d36c834373e5aac59) methods to the interface.
