### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by renehauck** [kyle-mccarthy/nest-next#29]
Hi,

is there an example for the cache of nextjs pages with this module?
I couldn't find one in the example folder?
Thanks a lot :smiley:

**Comment by kyle-mccarthy** [comment]
Previously I did have caching included in the example, but it was kind of out of the scope and complicated the "getting started" phase. [If you go back to this commit](https://github.com/kyle-mccarthy/nest-next/tree/a2c36bd54f016320c383fe9f5e4db18511a2ea0e/example/src), you can see how I previously was doing caching with redis. LMK if that is helpful and I can try to include it in the wiki or docs.
