### ISSUE TITLE
Jest Test Fails for CacheConfigService

### ISSUE THREAD

**Issue by GargantulaKon** [kyle-mccarthy/nest-next#3]
For the example project, it could be something wrong with my configuration on my end, but I have an initial failing Jest test when running the test suite with no changes.

This is the error that I get: 

> Nest can't resolve dependencies of the CacheConfigService (?). Please make sure that the argument at index [0] is available in the TestModule context.

In addition, for the constants.sts file, I get an error for the line in there: I'm running the Jest VSCode extension so it might be the run that notified me of the error.

> Cannot find module '@server/render/constants'

**Comment by kyle-mccarthy** [comment]
Hi I have added a mock for the ConfigService that was missing in that test file and removed that old file reference, I closed it via #4
