### ISSUE TITLE
How to deploy an app

### ISSUE THREAD

**Issue by staszewski** [kyle-mccarthy/nest-next#36]
**Describe the bug**
There is no info in readme how to deploy an app

**Expected behavior**
I'm trying to deploy app by myself but i have problems what steps to follow. It would be great to have this info in README

**To Reproduce**

Repository URL: 

**Version**
- next.js:
- nest:
- nest-next: 

**Additional context**
If i make it work by myself i will try to make pr for that, but for now it would be great to have some basic information how to approach this.

**Comment by kyle-mccarthy** [comment]
The deployment depends on how you set your app up, for the [basic example](https://github.com/kyle-mccarthy/nest-next/blob/master/examples/basic/package.json) you would just do `yarn build` and then can run the built files with `yarn dev`. 
LMK if this answers your question. When I have some free time, I can add a Dockerfile to the example which would make it a little more straightforward.

**Comment by kuriel-trivu** [comment]
How to deploy it for Vercel?

"errorMessage":"Error: > Couldn't find a `pages` directory. Please create one under the project root"

there are pages folder at root dir:

![image](https://user-images.githubusercontent.com/46456105/155195445-b2b2f747-a415-49e1-ae67-4adea0e4536d.png)

**Comment by kusaljr** [comment]
> How to deploy it for Vercel?
> 
> "errorMessage":"Error: > Couldn't find a `pages` directory. Please create one under the project root"
> 
> there are pages folder at root dir:
> 
> ![image](https://user-images.githubusercontent.com/46456105/155195445-b2b2f747-a415-49e1-ae67-4adea0e4536d.png)

Have you found solution for this?

**Comment by kyle-mccarthy** [comment]
@kusaljr this library is not compatible with Vercel. Specifically, any Next.js setups that use a custom server cannot be deployed to Vercel. See the Next docs about a custom server https://nextjs.org/docs/advanced-features/custom-server
