### ISSUE TITLE
Monorepo example production build always send 404 page

### ISSUE THREAD

**Issue by Xilel** [kyle-mccarthy/nest-next#40]
**Describe the bug**
I have tried to use monorepo example. It's work fine in development, but production build always send 404 page. It's don't matter what page you ask (index or about).

**Expected behavior**
Render page what set in @Render decorator.

**To Reproduce**

Repository URL: https://github.com/kyle-mccarthy/nest-next/tree/master/examples/monorepo
1. In server directory: yarn install && yarn build
2. In ui directory: yarn install && yarn build
3. In server directory: yarn start
4. Open in browser http://127.0.0.1:3000

**Version**
- next.js: 9.1.6
- nest: 6.10.12
- nest-next: 9.1.0

**Comment by Joebob12** [comment]
I have this issue as well so it's not just you.

**Comment by kyle-mccarthy** [comment]
@boenrobot would you be able to look into this? I don't have experience with using the mono repo.

**Comment by kyle-mccarthy** [comment]
@Joebob12 @Xilel I wanted to provide you an update. In #42 a user identified the problem, the viewsDir isn't correctly set. Using the file structure `/pages/views/{page here}` should resolve the problem. Alternatively, you can set the view `viewsDir` to end empty string.

**Comment by Xilel** [comment]
I confirm, #42 solution work.
