### ISSUE TITLE
Remove the use of this.app.useGlobalFilters, Warning RendererService is a singleton 

### ISSUE THREAD

**Issue by Rmannn** [kyle-mccarthy/nest-next#5]
Hello, thank you for this lib,

Actually, each route is binded to the renderer, It would be interesting to to be able to configure the url to handle via next and others via nest.
Trying to make an ajax request from browser to server ends in a "Not implemented" response.

Tell me if I am wrong, the renderer service is a singleton as the nest js module specification says. When an incoming request happens, you store the request and the response on the singleton `this.service.next(req, res)`. But this request and response might be replaced by an other request...

**Comment by kyle-mccarthy** [comment]
I thanks for checking it out! I just want to make sure that I understand, are you wanting to have a specific route which conditionally returns the rendered react page or returns some other data? Something like this?

```
@Controller('page')
export class PageController {

  @Get()
  index() {
    // perform SSR or return JSON?
  }

}
```

Regarding your second point, services are singletons in next... So you may be right, let me verify this in the morning (CST).

**Comment by Rmannn** [comment]
Exactly, I found that It was not possible at all cause the RenderFilter was sending the whole traffic to next.
I have extended the RenderFilter catch method to suit my needs, an example:
```typescript
    /**
     * Nest isn't aware of how next handles routing for the build assets, let next
     * handle routing for any request that isn't handled by a controller
     * @param err
     * @param ctx
     */
    public async catch(err: any, ctx: ArgumentsHost) {
        const http = ctx.switchToHttp();
        const req = http.getRequest();
        const res = http.getResponse();

        if (req.get('Content-Type') === 'application/json') {
            if (err.status) {
                res.status(err.status);
            }
            res.set(err.headers).json(err.response ? err.response : err);
        } else if (err.response === undefined) {
            const { pathname, query } = parseUrl(req.url, true);
            await this.errorRenderer(err, req, res, pathname, query);
        } else {
            await this.requestHandler(req, res);
        }
    }
```
Since we can't override the filter, It would be great to be able to pass a custom RenderFilter.
Thx

**Comment by kyle-mccarthy** [comment]
Thanks for providing me with this extra information. I have been thinking about this, and while I can provide a way for you to pass in your own filter implementation, what if I exposed a render method that you could call directly?  I was thinking something along the lines of this...

```
@Controller('page')
export class PageController {

  constructor(private readonly renderer: RendererService) {}

  index(@Req() req, @Res() res) {
    if (...) {
      // return some json
    }
    return this.renderer.render(req, res, 'YourView');
  }
}
```

The render method on the RenderService could then handle applying a prefix if you have one set, and would optionally accept a fourth argument for the initial props.

I was thinking this may be easier for you to maintain, but if you would prefer a custom filter option I could do that as well.

Also addressing your second point from the initial post, I have verified this is conceptually possible and will be pushing a new version today.

**Comment by kyle-mccarthy** [comment]
@Rmannn I released a new version that exposes the render method on the response object. This should allow for you to do what you were wanting without needing to modify or pass a custom filter. You can see #6 for the details!

**Comment by Rmannn** [comment]
Thank you ! I will check it
