### ISSUE TITLE
Dynamic routes. strange error

### ISSUE THREAD

**Issue by YuraGB** [kyle-mccarthy/nest-next#50]
"nest-next": "^9.2.0",

The issue is in dynemic route:
 - Expected behavior: 
in app.controller.ts
` 
@Get('category/:test')
  public category(@Res() res: RenderableResponse) {
      res.render('category/[...test]');
  }`

in the component : 
` <Link href='/category/[test]' as='/category/negligence'>`

I want that [...test].tsx in pages/views/category/[...test].tsx  render withought any issues
when the "/category/negligence" Link was clicked

observes : 
an error : Unhandled Runtime Error
Error: The provided `as` value (/category/negligence) is incompatible with the `href` value (/views/category/[...test]). Read more: https://err.sh/vercel/next.js/incompatible-href-as
![Selection_999(416)](https://user-images.githubusercontent.com/26120957/85933638-fbceae00-b8e1-11ea-9f05-06c7007f5cc8.png)

**Comment by kyle-mccarthy** [comment]
I haven't personally used catchall routes is next before, but I think your link is supposed to be like this:

```
<Link href='/category/[...test]' as='/category/negligence'>
 ...
</Link>
```

Note the change to the href.

See https://github.com/vercel/next.js/blob/canary/examples/catch-all-routes/components/header.js

Also if you are using [the default "viewsDir"](https://github.com/kyle-mccarthy/nest-next#settings) you will need all of your hrefs to be prefixed by views link so:

```
<Link href='/views/category/[...test]' as='/category/negligence'>
 ...
</Link>
```

The reason for that is nextjs expects the pages to be served directly out of /pages and not a sub directory. In the next major release I am going to make the "viewsDir" option to default to null to stay consistent with nextjs.

**Comment by YuraGB** [comment]
Greetings, Kyle! 
I'm glad that you had time to answer so quickly.

>  ...but I think your link is supposed to be like this:...

I am using it. I just copied smallest part of what I think is the most important.

>...you will need all of your hrefs to be prefixed by views link so:... 

I confirm that if add prefixes into 'href' and into 'as' fields the code will work without error.

>The reason for that is nextjs expects the pages to be served directly out of /pages and not a subdirectory

I have noticed it. I needed to put some functionality into __app.tsx and discovered that the file should be placed one Lvl above.

Note: It would nice if you write down some additional info about these dynamic routes into ReadMe file that others could easily find it and figure it out what's wrong.

Cheers, Yurii.

**Comment by kyle-mccarthy** [comment]
I agree that the docs could use a little work! I want to put together some sort of FAQ when I have time. I am hoping when I transition the default viewsDir to null it will make things more intuitive by removing opinionated code and deferring the next's styles.
