### ISSUE TITLE
local development env works error

### ISSUE THREAD

**Issue by yangzhennupt** [kyle-mccarthy/nest-next#51]
**Describe the bug**
I try to update next to 9.4.2,  found  local development *.js *.css report 404 error 

**Expected behavior**

example  :
Request URL: http://localhost:8080/_next/static/development/pages/views/Index.js?ts=1593354583846

got httpCode 404

**To Reproduce**

Repository URL: 

**Version**
- next.js: 9.4.2
- nest: 6.8.3
- nest-next: 9.2.0

**Additional context**

**Comment by kyle-mccarthy** [comment]
Can you provide additional information? I just checked and everything works as expected with `next@latest`.

**Comment by yangzhennupt** [comment]
my package.json dependencies   

 "@nestjs/common": "6.8.3",
    "@nestjs/core": "6.8.3",
    "@nestjs/platform-express": "6.8.3",
    "@nestjs/swagger": "3.1.0",
    "@types/uuid": "3.4.6",
    "@zeit/next-css": "1.0.1",
    "@zeit/next-less": "1.0.1",
    "axios": "0.19.2",
    "babel-polyfill": "6.26.0",
    "cookie": "0.4.0",
    "cookie-parser": "1.4.4",
    "helmet": "3.21.1",
    "isomorphic-unfetch": "3.0.0",
    "js-cookie": "2.2.1",
    "less": "3.10.3",
    "nest-next": "^9.2.0",
    "next": "^9.4.4",
    "next-compose-plugins": "2.2.0",
    "next-images": "1.2.0",
    "qs": "6.9.1",
    "raf": "3.4.1",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "reflect-metadata": "0.1.12",
    "rimraf": "2.6.2",
    "rxjs": "6.3.3",
    "swagger-ui-express": "4.1.2",
    "uuid": "3.3.3"

---------------------------
main.ts   

const nestServer = await NestFactory.create<NestExpressApplication>(AppModule);

----------------------------
app.module.ts


const agent = new http.Agent({
  keepAlive: true
});
@Module({
  imports: [RenderModule.forRootAsync(Next({ dev: process.env.NODE_ENV !== 'production' })), HttpModule.registerAsync({
    // imports: [REQUEST],
    useFactory: async (req: Request) => {
      const request: any = {
        timeout: 2000,
        maxRedirects: 5,
        httpAgent: agent,
        headers: cleanNil({
          // ...headers,
          // 'content-type': 'application/json',
          // @ts-ignore
          'user-agent': req.headers['user-agent'],
          // @ts-ignore
          referer: req.headers.referer,
          // @ts-ignore
          cookie: req.headers.cookie,
        }),
      };

      return request;
    },
    inject: [REQUEST],
  })],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_FILTER,
      useClass: HttpExceptionFilter,
    },
  ],
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer): any {
    consumer.apply(LoggerMiddleware)
      .forRoutes('');
  }
}

**Comment by kyle-mccarthy** [comment]
What does you `HttpExceptionFilter` class look like? nest-next adds its own global filter that is responsible for catching requests and forwarding them nextjs. It looks like you are overriding our [RenderFilter](https://github.com/kyle-mccarthy/nest-next/blob/master/lib/render.filter.ts).

**Comment by yangzhennupt** [comment]
```typescript
import { ArgumentsHost, BadRequestException, Catch, ExceptionFilter, HttpException } from '@nestjs/common';
import { ApiException } from '../exceptions/api.exception';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: any, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();
    const status = exception.getStatus();
    if (exception instanceof ApiException) {
      response
        .status(status)
        .json({
          success: false,
          error_code: exception.getCode(),
          error_msg: exception.getMessage(),
        });
    } else {
      response
        .status(status)
        .json({
          success: false,
          error_code: 500,
          error_msg: exception.getMessage && exception.getMessage() || 'unknow error'
        });
    }
  }

}
```

**Comment by yangzhennupt** [comment]
@kyle-mccarthy   I got it .  
my global filter has not ignore these static resources request which need by nest-next ; 
nest got exception and then I just ended this response;
