### ISSUE TITLE
How todo aliasing of nestjs module?

### ISSUE THREAD

**Issue by gaurav-bothra** [kyle-mccarthy/nest-next#52]
Hi,

Thanks for creating this amazing lib. I am trying to add nest-next lib in my existing project. But I am not able to aliasing in nestjs.

**tsconfig.json**

`
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "jsx": "preserve",
    "pretty": true,
    "noImplicitAny": true,
    "alwaysStrict": true,
    "strictNullChecks": false,
    "strict": false,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "outDir": ".next",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "lib": [
      "es2017",
      "dom"
    ],
    "baseUrl": "./server",
    "typeRoots": [
      "node_modules/@types",
      "./typings"
    ],
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "paths": {
      "@environments": ["environments"],
      "@utils": ["utils"],
      "@shared": ["shared"]
    }
  },
  "include": [
    "./pages/**/*",
    "server/**/*", "node_modules/src"
  ],
  "compileOnSave": false,
	"exclude": [
		"node_modules"
	]
}
`

**tsconfig.server.json**

`
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": ".next/production-server",
    "declaration": true,
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "isolatedModules": true,
    "noEmit": false,
    "allowJs": false,
    "paths": {
      "@environments": ["environments"],
      "@utils": ["utils"],
      "@shared": ["shared"]
    }
  },
  "include": ["./server/**/*"],
  "exclude": ["node_modules"]
}
`

**tsconfig-paths-bootstrap.js**

`
const tsConfig = require('./tsconfig.server.json');
const tsConfigPaths = require('tsconfig-paths');
const baseUrl = './server'; // Either absolute or relative path. If relative it's resolved to current working directory.
tsConfigPaths.register({
  baseUrl,
  paths: tsConfig.compilerOptions.paths,
});
`

**Comment by kyle-mccarthy** [comment]
How are you actually running the server? I am not sure if the aliasing is directly related to nest-next, you may want to checkout [this article](https://dev.to/rubiin/resolving-path-alias-in-nestjs-projects-11o1).

**Comment by kyle-mccarthy** [comment]
I am going to close this issue since more information wasn't provided and it doesn't seem related to this lib.

**Comment by gaurav-bothra** [comment]
Hi @kyle-mccarthy 

I already setup alias path in tsconfig.server.json file but still I am getting error.

**Comment by gaurav-bothra** [comment]
Also When I remove alias package from main.ts

I am getting this error 

```
./src/environments\index.ts:6:31
Type error: Object is possibly 'undefined'.

  4 | const NODE_ENV: string = process.env.NODE_ENV || 'development'
  5 | const __PROD__: boolean = NODE_ENV==='development'?false:true
> 6 | const PORT: number = 4000 || +process.env.PORT;
    |                               ^
  7 | 
  8 | dotenv.config({ path: join(process.cwd(), `.env.${NODE_ENV}`) });
  9 | 
error Command failed with exit code 1.
```

**Comment by kyle-mccarthy** [comment]
This is a TS error unrelated to this package, you would probably get better (and quicker) assistance on a site like StackOverflow. However, with the information provided it looks like TS is telling you that process.env.PORT might be undefined and therefore you can't ensure the  number type. You may be able to resolve the issue with defining your PORT var like `const PORT: number = process.env.PORT || 4000;`
