### ISSUE TITLE
any chance of supporting next 10 ?

### ISSUE THREAD

**Issue by amir-arad** [kyle-mccarthy/nest-next#69]
they say there are "[no breaking changes](https://nextjs.org/docs/upgrading#upgrading-from-version-9-to-10)"
and it's a blocker from upgrading to react 17...

**Comment by kyle-mccarthy** [comment]
Hi, I actually believe that this works with `next@10`, `react@17` and `react-dom@17`. At least it worked as expected when I updated those packages on the [basic example](https://github.com/kyle-mccarthy/nest-next/tree/master/examples/basic). Did you have any specific problems when using next 10?

**Comment by amir-arad** [comment]
npm won't let me try because it violates peerDependencies... maybe a release with a more permissive versions range?

**Comment by kyle-mccarthy** [comment]
ah interesting, `yarn` didn't complain so I assumed `npm` wouldn't care.

I've published a new version (9.3) to allow for next 10. Let me know if it resolves the problem!

**Comment by amir-arad** [comment]
seems to work, thanks.
