### ISSUE TITLE
tests support (based on monorepo example)

### ISSUE THREAD

**Issue by amir-arad** [kyle-mccarthy/nest-next#70]
**Describe the bug**
the monorepo example does not support test (@nestjs/testing).

`Test.createTestingModule({imports: [AppModule]}).compile()` breaks:
`TypeError: Cannot set property 'render' of undefined
    at RenderService.bindHttpServer (.../node_modules/nest-next/dist/render.service.js:79:23)`
**Expected behavior**
not break, or supply another way to run e2e test
**To Reproduce**
sorry, it's a private repo, but really just try to load the server in test mode

**Version**
- next.js:10.0.3
- nest:6.4
- nest-next: 9.3

**Additional context**
the nest test tool defers loading of http server, so at `.compile()` time it is still undefined. perhaps the render service can detect such a scenario and instead of replacing the render function it can hook into some later point when the server exists?

**Comment by kyle-mccarthy** [comment]
So I think you will have to register the RenderModule differently for testing, it's a little bit more of a manual process that we [previously use to recommend](https://docs.nestjs.com/fundamentals/testing#end-to-end-testing). Then in the actual test it would be similar to how the [e2e testing example](https://docs.nestjs.com/fundamentals/testing#end-to-end-testing) in nest works.  I haven't tested this code but something along these lines should work.


__application.module.ts__
```
import { Module } from '@nestjs/common';
import { RenderModule } from 'nest-next';

@Module({
  imports: [
    RenderModule,
    ...
  ],
  ....
})
export class AppModule {}
```

__your-test.spec.ts__
```
import { RenderModule } from 'nest-next';
import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';

describe('Test', () => {
  let app: INestApplication;
  let catsService = { findAll: () => ['test'] };

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    })
    .compile();

    app = moduleRef.createNestApplication();
    await app.init();

    const nextApp = Next({ dev });
    await nextApp.prepare();

    const renderer = app.get(RenderModule);
    renderer.register(app, nextApp);
  });

  ...
});
```

The reason that it doesn't work using the `forRootAsync` method of registering the module, is that factory that creates the RenderService provider [expects to be able to get the HttpAdapterHost](https://github.com/kyle-mccarthy/nest-next/blob/master/lib/render.module.ts#L33) which is apparently undefined when compiling the testing module.

**Comment by amir-arad** [comment]
I'm trying to go in that direction and I get this error:
```
 ●  process.exit called with "1"

      14 |         }).compile();
      15 | 
    > 16 |         app = moduleRef.createNestApplication();
         |                         ^
      17 |         await app.init();
      18 | 
      19 |         const nextApp = Next({ dev: true, dir: path.resolve(__dirname, '../../ui') });

      at Object.loadPackage (../../node_modules/@nestjs/common/utils/load-package.util.js:13:17)
      at TestingModule.createHttpAdapter (../../node_modules/@nestjs/testing/testing-module.js:25:56)
      at TestingModule.createNestApplication (../../node_modules/@nestjs/testing/testing-module.js:13:43)
      at Object.<anonymous> (app2.e2e.spec.ts:16:25)
      ```

**Comment by amir-arad** [comment]
also, can you explain the "magic" behind importing `RenderModule` itself and not the result of `RenderModule.forRootAsync(...)`? where does it get the `Next` server and `{ viewDirs }` config from at runtime?
I'm new to nest, so this might be too trivial?

**Comment by amir-arad** [comment]
thanks!
I havent figured out how to pass the configuration options (specifically `viewsDir`)

**Comment by kyle-mccarthy** [comment]
I had previously used the wrong link for the old documentation, I've updated it in my previous comment, it was supposed to point here: https://github.com/kyle-mccarthy/nest-next/blob/f8dd9f3ce3f537b80b8afe8019da63bdccc1de17/README.md#import-and-register-the-rendermodule

Also, the [register method](https://github.com/kyle-mccarthy/nest-next/blob/08426c74a94d59cc5d9742fc3d4d4931b1b3a75f/lib/render.module.ts#L74) accepts an optional third parameter for the config options (the `viewsDir`).

**Comment by amir-arad** [comment]
It works!
Thanks again.

do you think it can be done without using the deprecated `RenderModule.register()` ?

**Comment by amir-arad** [comment]
Looking at #54 I guess it's a duplicated issue
