### ISSUE TITLE
404 on dynamic routes or path error using urls

### ISSUE THREAD

**Issue by billalouaali** [kyle-mccarthy/nest-next#71]
Hello guys,

i'm facing a little problem since many days now and i don't figure how to fix it.

I have /pages/views/publication/[slug].tsx, when i try to access it using Link or by the direct url link, i got a : Error: The provided `as` value (/publication/my-super-url) is incompatible with the `href` value (/views/publication/[slug]);

to access it by Link i use :

`<Link href={`views/publication/[slug]`} as={`/publication/${publication.slug}`}></Link>`

since the error comes from the incompatible href, i tried to change the viewsDir and set it to null and see if i can play with the paths. After setting the path to null and moved my folder to pages/publication/[slug].tsx it works, but i would like to put it in pages/views

my app.controller with viewDir set to null:

```
    @Get('publication/:slug')
    @Render(`publication/[slug]`)
    public publicationSlug() {}
```

**Version**
next: 9.5.5
nest-next: 9.3.0
nest: 6.13

**Comment by kyle-mccarthy** [comment]
Hi, this is a good question and wasn't previously documented very well. I updated the basic example to show how to get next's dynamic routing working correctly.

[The post preview component](https://github.com/kyle-mccarthy/nest-next/blob/master/examples/basic/components/post-preview.tsx) shows how to setup the `Link` component with the correct `href` and `as` values.

[The blog controller](https://github.com/kyle-mccarthy/nest-next/blob/master/examples/basic/src/blog/blog.controller.ts) shows how the dynamic routes should be setup in nest.

There are two primary parts:
1. make sure the controller is using the right view path, and getting the slug param correctly
2. make sure that your link has the correct `href` and `as` props

The following assumes that your project structure looks like this

```
pages/views/publication/[slug].tsx
src/blog/blog.controller.ts
```

__blog.controller.ts__
```
@Controller('/publication')
export class PublicationController {

  @Render('publication/[slug]')
  @Get(':slug')
  public publicationSlug(@Param('slug') slug: string) {
    ...
  }
}
```

__linking to dynamic page__
```
<Link
  href={{
    pathname: '/views/publication/[slug]',
    query: { slug: publication.slug },
  }}
>...</Link>
```

**Comment by billalouaali** [comment]
Hello kyle,

thanks for the answer, i'm not sure to see the difference between mine, and the way that you handle dynamic request on your blog.controller.ts, i tried to move my publication/[slug].tsx in pages so i have pages/views/publication/[slug].tsx with this configuration, the url path expected should be /publication/my-publication-slug so i have :

`RenderModule.forRootAsync(Next({ dev: process.env.NODE_ENV !== 'production' }))`

```
@Controller('/publication')
export class AppController {

    @Get(':slug')
    @Render(`publication/[slug]`)
    public publicationSlug() {}

}
```
and for some reason i'm still getting : Uncaught (in promise) Error: The provided `as` value (/publication/my-publication-slug) is incompatible with the `href` value (/views/publication/[slug]).

Notice that the problem only appear when i try to load the page with the url directly, using a next.js `<Link>` without /views like so :
`<Link href={`/publication/[slug]`} as={`/publication/${publication.slug}`}>` works perfectly

**Comment by kyle-mccarthy** [comment]
> Notice that the problem only appear when i try to load the page with the url directly

When you say this do you mean that you are navigating to the page directly, as in typing in the URL to your browser and getting the error?

> `<Link href={/publication/[slug]} as={/publication/${publication.slug}}>` works perfectly

When using it like this, if you look in your console do you see the prefetch 404ing?

--- 

Can you try using the Link component like this instead?

```
<Link
  href={{
    pathname: '/views/publication/[slug]',
    query: { slug: publication.slug },
  }}
  as={`/publication/${publication.slug}`}
>...</Link>
```

**Comment by billalouaali** [comment]
> When you say this do you mean that you are navigating to the page directly, as in typing in the URL to your browser and getting the error?

Yes, i'm mean by that, typing the url in my browser, after that the error shows up

> When using it like this, if you look in your console do you see the prefetch 404ing?

No i don't see any error in my network/console

> Can you try using the Link component like this instead?

```
<Link
  href={{
    pathname: '/views/publication/[slug]',
    query: { slug: publication.slug },
  }}
  as={`/publication/${publication.slug}`}
>...</Link>
```

so i have /pages/views/publication/[slug].tsx, by using the`<Link>`code before, and setting viewsDir to null (or not defining it works as well), i can navigate to the page

concerning typing the url in my browser :

setting viewsDir to null and having : 

```
@Controller()
export class AppController {

    @Get('publication/:slug')
    @Render('views/publication/[slug]')
    public publicationSlug() {}

}
```

i got the error : `Error: The provided as value (/publication/my-super-url) is incompatible with the href value (/views/publication/[slug]);`

By not setting viewsDir and having the same configuration than before it returns a 404.

Upgrading next to 10 doesn't change anything unfortunately.

To resume, the error appear only when publication folder is inside page/views, playing with viewsDir always return a 404 or the path error...

**Comment by kyle-mccarthy** [comment]
Okay I am having a little trouble helping since I don't have access to your code. 

First, can you look at the [example that I provide in the basic example](https://github.com/kyle-mccarthy/nest-next/tree/master/examples/basic)? The immediately relevant files are listed below, but you may want to check and make sure the config is the same (for example I don't change the viewsDir).

- Controller + method handling the dynamic page: https://github.com/kyle-mccarthy/nest-next/blob/e9a948686738bad215aa2a1be1c348a9d40575dd/examples/basic/src/blog/blog.controller.ts#L22
- The dynamic next page: https://github.com/kyle-mccarthy/nest-next/blob/master/examples/basic/pages/views/blog/%5Bslug%5D.tsx
- Linking to one of the dynamic pages: https://github.com/kyle-mccarthy/nest-next/blob/e9a948686738bad215aa2a1be1c348a9d40575dd/examples/basic/components/post-preview.tsx#L22

If you still have issues after that, can you provide a minimal example as a git repository detailing the issue? I can clone it then and try to provide some additional help. I won't be able to immediately do this but should have some free time in the next couple of days.

**Comment by billalouaali** [comment]
After some rework, i found that the issue were coming from the implementation of : 

```
export async function getStaticPaths() {
  const res = await fetch(`${process.env.API_URL}/publications`);
  const publications = await res.json();
  const paths = publications.map(publication => ({ params: { slug: publication.slug } }));

  return { paths, fallback: true }
}

export async function getStaticProps({ params }) {
  const res = await fetch(`${process.env.API_URL}/publications/${params.slug}`);
  const publication = await res.json();
  return {
    props: {
      publication
    },
  }
}
```

i don't know why the error talk about path and why this piece of code is defective but what ever... so i replaced it with getInitialProps and everything works as expected.

Thanks for your help and keep the good work 👍
