### ISSUE TITLE
support nest 7

### ISSUE THREAD

**Issue by amir-arad** [kyle-mccarthy/nest-next#72]
Is it possible to support nest 7?
using npm I get this error
```
npm ERR! While resolving: example-server@1.0.0
npm ERR! Found: @nestjs/common@7.6.5
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^7.6.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.4" from nest-next@9.3.0
npm ERR! node_modules/nest-next
npm ERR!   nest-next@"^9.3.0" from the root project
```

**Comment by kyle-mccarthy** [comment]
I can look into this, it doesn't look like this package uses any of the deprecated items so it could be as simple as bumping the versions of the peer dependencies.

**Comment by georgeadeishvili** [comment]
It would be nice if update will be soon.

**Comment by kyle-mccarthy** [comment]
@georgeadeishvili PRs are welcome!

**Comment by amir-arad** [comment]
Thanks you for the effort @kyle-mccarthy 
This is a really sweet library
