### ISSUE TITLE
Static Files?

### ISSUE THREAD

**Issue by dustinlacewell** [kyle-mccarthy/nest-next#74]
How to use static files? File in `public/` don't seem to be noticed.

**Comment by kyle-mccarthy** [comment]
Checkout out #48 for some options for serving the static files. Basically, there are a couple of approaches, and I attempted to solve the issue [here](https://github.com/kyle-mccarthy/nest-next/issues/38#issuecomment-647867509). I think that this is _probably_ an adequate solution, but I wanted to get community feedback before mastering the changes.

**Comment by kyle-mccarthy** [comment]
This functionality can be enabled using the [pass through-404s](https://github.com/kyle-mccarthy/nest-next#pass-through-404s).
