### ISSUE TITLE
Basic example fails to build

### ISSUE THREAD

**Issue by thisismydesign** [kyle-mccarthy/nest-next#75]
**Describe the bug**

I'm trying to add a reproducible setup to the basic example via Docker. Can't seem to build the example project.

```sh
cd examples/basic
docker build --tag nest-next-basic .
```

`Dockerfile`
```
FROM node:14-alpine

WORKDIR /app

COPY package.json /app
RUN yarn install

COPY . /app

EXPOSE 3000

RUN yarn build
```

```
#8 3.690 Failed to compile.
#8 3.690 
#8 3.690 ./src/application.module.ts:13:9
#8 3.690 Type error: Type '{ useFilesystemPublicRoutes: false; }' is not assignable to type 'NextConfig'.
#8 3.690   Type '{ useFilesystemPublicRoutes: false; }' is missing the following properties from type '{ i18n?: { locales: string[]; defaultLocale: string; domains?: DomainLocales | undefined; localeDetection?: false | undefined; } | null | undefined; headers?: (() => Promise<Header[]>) | undefined; ... 4 more ...; experimental: { ...; }; }': future, experimental
#8 3.690 
#8 3.690   11 |       Next({
#8 3.690   12 |         dev: process.env.NODE_ENV !== 'production',
#8 3.690 > 13 |         conf: { useFilesystemPublicRoutes: false },
#8 3.690      |         ^
#8 3.690   14 |       }),
#8 3.690   15 |     ),
#8 3.690   16 |   ],
#8 3.705 error Command failed with exit code 1.
```

**To Reproduce**

Repository URL: https://github.com/thisismydesign/nest-next/tree/add-docker-to-basic-example

**Version**

As defined in the example.

    "nest-next": "^9.3.0",
    "next": "10",

**Comment by kyle-mccarthy** [comment]
This is interesting... are you getting this error when building locally too? Or is it limited to the container?

**Comment by thisismydesign** [comment]
I don't have a local setup, just docker. I noticed you don't have `yarn.lock` committed or a docker setup. I think it would be great to have a reproducible setup as I don't think the current one is reliable long term.

FWIW if I ignore the offending file from TS, the example works fine.

**Comment by kyle-mccarthy** [comment]
I agree with you about both the yarn.lock and dockerfile, that is a good idea. I will work on getting a Dockerfile working locally, which will hopefully resolve the issue.

Before I am able to do that though, you should be able to typescript to stop erroring out with the following:

```
Next({
  dev: process.env.NODE_ENV !== 'production',
  conf: { useFilesystemPublicRoutes: false } as any,
}),
```

Note that this isn't considered good practice but I don't want to block your ability to make progress.

**Comment by thisismydesign** [comment]
Thank Kyle, yes, working around the TS issue is a good temporary solution for me.
