### ISSUE TITLE
Cannot destructure property 'inAmpMode'

### ISSUE THREAD

**Issue by javeoff** [kyle-mccarthy/nest-next#80]
`Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.
    at Html (webpack-internal:///./node_modules/Next/dist/pages/_document.js:168:13)
`

This error handled in a starter project by tutorial. Without module i don't have an error. System: Mac os 12 arm

**Comment by kyle-mccarthy** [comment]
Can you provide a reproducible example on https://codesandbox.io? Your stack trace shows the error coming from `next` rather than from this package.

**Comment by javeoff** [comment]
Hello, Kyle! I tried to write my own code. After i had an error and just cloned this project. It was similar to my case and error repeated again. That's project https://github.com/Skn0tt/nextjs-nestjs-integration-example

Now i try to start example from your repository

**Comment by javeoff** [comment]
I can't started a basic example from this project too. All the time i tried to solve the new problem.
Probably, really, problem in the `next`, but i don't change version in example's package.json.

npm version 7.7.6
node version (it was 14, but after update have no changes) now is 15.14.0

`Type '{ useFilesystemPublicRoutes: false; }' is not assignable to type 'NextConfig'.
  Type '{ useFilesystemPublicRoutes: false; }' is missing the following properties from type '{ i18n?: { locales: string[]; defaultLocale: string; domains?: DomainLocales | undefined; localeDetection?: false | undefined; } | null | undefined; headers?: (() => Promise<Header[]>) | undefined; ... 4 more ...; experimental: { ...; }; }': future, experimental

13         conf: { useFilesystemPublicRoutes: false },
           ~~~~

  node_modules/next/dist/next-server/server/next-server.d.ts:30:5
    30     conf?: NextConfig | null;
           ~~~~
    The expected type comes from property 'conf' which is declared here on type 'NextServerConstructor'
`

**Comment by javeoff** [comment]
Sorry. I sent wrong example) Look, this is my example. I cant started this code in my second macos device too (not m1, but mac os 12)
https://github.com/javeoff/nest-next-boilerplate

**Comment by javeoff** [comment]
Issue in next version, just change to "next": "^11.0.1",
Problem can be closed. Thank you for your attention, Kyle!
If you will understand why in the last next version error is thrown, pls, create issue there, thanks)

**Comment by tahmeednabi** [comment]
For anyone wanting to use latest version of next, I solved the issue for myself.

I was trying to recreate the monorepo example of the next-next project, however, with the latest version of next, both server and client need to be using the same next module, so I simply ran `yarn remove next` in both client and server, and `yarn add next` in the root repository. Should work fine after that.
