### ISSUE TITLE
path.normalize doesn't works on windows

### ISSUE THREAD

**Issue by vvkuzma** [kyle-mccarthy/nest-next#82]
**Describe the bug**

File **render.service.ts**  - method **getViewPath(view: string)** 
On Windows OS  the use of **path.normalize()** causes an Next.js  error like: **"Cannot render page with path "\index"**

Basically it overrides the path. Changes all "/" symbols to the "\\" and add "\\" at the start of the path f.e:

'blog/posts' =>'\blog\posts'
'index' => '\index'

And next.js can't correctly resolve this new path with backslashes.

**Possible solution**
Split by default separator and join by "/". It will work on Windows:

return path.normalize(`${basePath}/${view}`).split(path.sep).join("/");

**Comment by kyle-mccarthy** [comment]
@vvkuzma thank you for submitting this bug report. I don't have a windows machine to test on, would you be able to verify that the code below outputs the correct path?

```
const path = require('path');
const output = path.posix.normalize("/path/to/file");
console.log(output);
```

**Comment by vvkuzma** [comment]
@kyle-mccarthy thank you for Your response.

I tested the code above on windows and all is ok.

path.posix.normalize("/path/to/file");  - works fine
Returned path is as expected -  "/path/to/file".

Regards

**Comment by kyle-mccarthy** [comment]
Hi @vvkuzma [I published a new version](https://www.npmjs.com/package/nest-next/v/9.6.0) with a fix for this!
