### ISSUE TITLE
Next.js 12 hmr

### ISSUE THREAD

**Issue by i-tengfei** [kyle-mccarthy/nest-next#86]
After upgrading to Next.js 12, I'm getting the following error while running the app in dev mode:

```
WebSocket connection to 'ws://localhost:3000/_next/webpack-hmr' failed: 
```

**Version**
- next.js: v12.1.0
- nest: v8.0.0

Next.js used a server-sent events connection to receive HMR events. Next.js 12 now uses a WebSocket connection.

https://github.com/vercel/next.js/pull/30704/files#diff-0220ca71b6e5d1c80ad9e3dedd642059ed9a26c2a5ae414e46f022d2e688c9a6R61

**Comment by kyle-mccarthy** [comment]
Hey, thanks for letting me know about this; I wasn't aware of the problem. I will try to look into this, but if anyone wants to propose a PR in the meantime, I encourage them to do so!

**Comment by yakovlev-alexey** [comment]
Hello! I actually would like to help with this issue. However I was unable to reproduce it on my computer. I used this repository - https://github.com/yakovlev-alexey/nest-next-example/tree/next-12 - on the branch `next-12`. In my case connection to `ws://localhost:3000/_next/webpack-hmr` was established successfully and HMR worked as intended in MacOS Chromium 95.

@i-tengfei, could you please provide steps to reproduce the issue you are facing? A repository with reproduction steps would be perfect. OS and browser could also be an important piece of information. And, perhaps, try cloning my repository to see if it works there.

**Comment by i-tengfei** [comment]
this repository -  `https://github.com/yakovlev-alexey/nest-next-example/tree/next-12` works for me.
I'll try to find out what's different between the two, thanks guys.
