### ISSUE TITLE
Not able to reach nest endpoints.

### ISSUE THREAD

**Issue by Yannickvandenbos** [kyle-mccarthy/nest-next#90]
**Describe the bug**
I have authentication setup in my nest project. 
In my app.controller.ts I have all my view endpoints (needs to be handled by next) and one login endpoint (needs to be handled by nest). Everytime I try to reach the login endpoint, I get a next 404 error page in return instead of the expected JSON TOKEN. 

**Expected behavior**
Returning JSON TOKEN if credentials are correct. 

`@Controller()
export class AppController {
  constructor(private readonly authService: AuthService) {}

  @Get('/')
  @Render('index')
  home() {
    return {};
  }

  @Get('/posts')
  @Render('posts')
  posts() {
    return {};
  }

  @Get('/posts/new')
  @Render('posts/new')
  newpost() {
    return {};
  }

NOT REACHABABLE, GET 404 NEXT PAGE 
  **@UseGuards(AuthGuard('local'))
  @Post('/v1/api/auth/login')
  async login(@Request() req) {
    return this.authService.login(req.user);
  }**
}`

**Comment by okhomenko** [comment]
Hey @Yannickvandenbos. Did you figure out how to make it work?
