### ISSUE TITLE
Module-wide type error (Fix included)

### ISSUE THREAD

**Issue by barbarbar338** [kyle-mccarthy/nest-next#91]
Since the typing source is not specified, a type error is received in editors such as VSCode. Need to add 
```json
"typings": "index.d.ts"
```
into package.json. IDK if repo is still maintained so created an issue instead of creating a PR.

**Comment by kyle-mccarthy** [comment]
Hey this repo is still maintained and I would love a PR. Would you mind opening one?

**Comment by barbarbar338** [comment]
Well it wasn't working properly for me until I add typings field yesterday but it works now sorry :D

**Comment by kyle-mccarthy** [comment]
Hey, please don't be sorry. I haven't been following typescript updates as closely recently. If this is a something that's beneficial to everyone I'd like to make sure it gets resolved.
